#!/bin/bash

export PATH="$(readlink -f ~/.toolbox/bin):$PATH"
export BRAZIL_WORKSPACE_DEFAULT_LAYOUT=short
alias bb=brazil-build
alias bba='brazil-build apollo-pkg'
alias bre='brazil-runtime-exec'
alias brc='brazil-recursive-cmd'
alias bws='brazil ws'
alias bwsuse='bws use --gitMode -p'
alias bwscreate='bws create -n'
alias bbr='brc brazil-build'
alias bball='brc --allPackages'
alias bbb='brc --allPackages brazil-build'
alias bbra='bbr apollo-pkg'

alias sam="brazil-build-tool-exec sam"
export SAM_ASSUME_ACCOUNT_ID="918395798573"

alias mwcert="ssh-keygen -L -f ~/.ssh/id_rsa-cert.pub"

