#!/usr/bin/env bash

debug "file: ${BASH_SOURCE[0]}"
return 0

o=" -verbose"
if is_debug; then
  o=" -debug"
fi

alias mount.gdrive="google-drive-ocamlfuse ${o} $(xdg-user-dir DOCUMENTS)"
alias umount.gdrive="fusermount -u $(xdg-user-dir DOCUMENTS)"
