#!/bin/bash
debug "file: ${BASH_SOURCE[0]}"

export TERM=xterm-256color

export CLICOLOR=1
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH

# coreutils
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

alias top=htop
