#!/bin/bash
debug "file: ${BASH_SOURCE[0]}"

export TERM=xterm-256color

export CLICOLOR=1
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8-default/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH

# coreutils
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# lesspipe
export LESSOPEN="|/usr/local/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1

# htop
alias top=htop
